# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pham Duc Tho
title: Son, Husband, Father, Lecturer, Developer and a Friend
email: thopd@vnu.edu.vn
website: thopd88.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  thopd88
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: thopd
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: thopd
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-4554-1540

# Additional icon links
additional_links:
- title: Web of Science
  icon: fab fa-wikipedia-w
  url: https://www.webofscience.com/wos/author/record/46065993
- title: Scopus
  icon: fab fa-wikipedia-w
  url: https://www.scopus.com/authid/detail.uri?authorId=57194155325

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pham-Duc Tho and I am a lecturer at the International School, Vietnam National University, with a PhD in Computer Science, specializing in Learning Technologies, and recognized for significant research contributions.

  I am most skilled in: <mark>PHP</mark> and <mark>Laravel</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Peer-Interaction Programming Learning System
        link: new.pipls.net
      - layout: top-middle
        title: Cùng Học
        link: cunghoc.net
      - layout: top-middle
        title: Hung Vuong University Virtual Tour
        link: 360.hvu.edu.vn/V1/
      - layout: top-middle
        title: Hung Vuong University LMS
        link: elearning.hvu.edu.vn/
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # description: | # this will include new lines to allow paragraphs
        #   I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: International School, Vietnam National University
        link: is.vnu.edu.vn
        # link_text: boringcompany.com
        # quote: >
        #   I am currently working at the International School, Vietnam National University, where I am a lecturer in the Department of Applied Sciences.
        description: | # this will include new lines to allow paragraphs
          I am currently working at the International School, Vietnam National University, where I am a lecturer in the Department of Applied Sciences. I am responsible for teaching and researching in the field of Learning Technologies and Software Engineering.
        sub_title: Lecturer
        caption: April 2024 - Present
      # - layout: right
      #   title: Greenwich University - Vietnam Campus
      #   link: greenwich.edu.vn
      #   # link_text: boringcompany.com
      #   sub_title: Part-time Lecturer
      #   caption: June 2021 - April 2024
      - layout: left
        title: Hung Vuong University
        link: hvu.edu.vn
        # link_text: boringcompany.com
        sub_title: Lecturer, Head of Software Engineering Department
        caption: August 2010 - April 2024
        description: | # this will include new lines to allow paragraphs
          I was responsible for teaching and researching in the field of Learning Technologies and Software Engineering. I was also the Head of the Software Engineering Department, where I was responsible for managing the department and ensuring the quality of the training program.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Dong Hwa University
        caption: 2014 - 2020
        sub_title: PhD in Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at National Dong Hwa University, I was working on my PhD in Computer Science, specializing in Learning Technologies. My research focused on the development of a Peer-Interaction Programming Learning System (PIPLS) to support students in learning programming through peer interaction.

          I spent a lot of my free time with my friends and family, exploring the beautiful landscapes of Taiwan, and learning about the culture and people of this country.
      - layout: left
        title: Hanoi University of Science and Technology
        caption: 2010 - 2012
        sub_title: Master in Computer Science
        description: | # this will include new lines to allow paragraphs
          During my time at Hanoi University of Science and Technology, I was working on my Master's degree in Computer Science. My research title is Research on the application of SOA architecture in enterprise environments.
      - layout: left
        title: Hung Vuong University
        caption: 2006 - 2010
        sub_title: Bachelor in Computer Science
        description: | # this will include new lines to allow paragraphs
          I attended Hung Vuong University in 2006, achieving the highest admission grade and graduating with top honors. I then stayed on to become a lecturer immediately after graduation.

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      I have published a number of research papers in international journals and conferences. Some of my most recent publications are:
      - Lai, C.-H., *Tho, P.-D.*. (2023). Design and Development of a Personalized Recommender System of Student Question-Generation Exercises for Programming Courses. Paper presented at the 31th International Conference on Computers in Education.
      - *Tho, P.-D.*, Lai, C.-H.. (2022). Exploring the Behavior Patterns of Students Accessing Online Learning Material in Online Course: A Case Study at Hung Vuong University. Paper presented at the 30th International Conference on Computers in Education.
      - *Tho, P.-D.*, Lai, C.-H., & Tai, T.-T. (2021). Exploring Student Behavior during Student-Generated Questions Activities on Programming Learning. Paper presented at the 29th International Conference on Computers in Education.
      - Lai, C.-H., & *Tho, P.-D.* (2020). The integration of Mobile Instant Messaging to a Peer-Interaction Programming Learning System. Paper presented at the The 28th International Conference on Computers in Education (ICCE 2020).
      - *Tho, P.-D.*, Lai, C.-H., & Navratil, O. (2020). Effect of Behavior Patterns of Accessing Learning Materials on Learning Performance in Student-generated Question Activities. Journal of Internet Technology, 21(1), 135-146.
      - Lai, C.-H., Lin, H.-W., Lin, R.-M., & *Tho, P.-D.* (2019). Effect of Peer Interaction among Online Learning Community on Learning Engagement and Achievement. International Journal of Distance Education Technologies (IJDET), 17(1), 66-77.
      - *Tho, P.-D.*, Cuong, N.-H., Kien, H.-C., & Lai, C.-H. (2018). Development of a Peer-Interaction Programming Learning System. Paper presented at the International Conference on Context- Aware Systems and Applications, and Nature of Computation and Communication, Vietnam.
      - Lai, C.-H., *Tho, P.-D.*, Navrátil, O., & Yang, S.-P. (2018). The use of web analytical tools to improve the student engagement in the context of industrial revolution 4.0. Paper presented at the International Conference on Teacher Education Renovation. 
      - Arunoprayoch, N., Lai, C.-H., *Tho, P.-D.*, Liang, J.-S., & Yang, J.-C. (2018). Effects of Question Types on Engagement and Performance of Programming Learning for Non-computer Science Majors. Paper presented at the 2018 7th International Congress on Advanced Applied Informatics (IIAI-AAI).
      - Arunoprayoch, N., Lai, C.-H., *Tho, P.-D.*, & Liang, J.-S. (2017). Effects of peer interaction on web-based computer programming learning. Paper presented at The 25th International Conference on Computers in Education (ICCE 2017).
      - Lai, C.-H., *Tho, P.-D.*, & Liang, J.-S. (2017). Design and evaluation of question-generated programming learning system. Paper presented at the 2017 6th IIAI International Congress on Advanced Applied Informatics (IIAI-AAI).
      - Lai, C. H., & *Tho, P.-D.* (2016). Development of a Programming Learning System Based on a Question Generated strategy. Paper presented at the 24th International Conference on Computers in Education, India.
      - *Tho, P.-D.*, Duc D.-V. (2014). Developing an advanced watermarking algorithm for street-network vector maps against scale attack. Paper presented at the 7th National Conference on Fundamental and Applied IT Research - FAIR'7


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Learning Technologies and Software Engineering, some of my other interests and hobbies are:
      - Spending time with my family
      - Exploring new ideas
      - Watching movies

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
