# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pham Duc Tho
title: Son, Husband, Father, Lecturer, Developer and a Friend
email: thopd@vnu.edu.vn
website: thopd88.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  thopd88
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: thopd
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: thopd
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-4554-1540

# Additional icon links
additional_links:
- title: Web of Science
  icon: fab fa-wikipedia-w
  url: https://www.webofscience.com/wos/author/record/46065993
- title: Scopus
  icon: fab fa-wikipedia-w
  url: https://www.scopus.com/authid/detail.uri?authorId=57194155325

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pham-Duc Tho and I am a lecturer at the International School, Vietnam National University, with a PhD in Computer Science, specializing in Learning Technologies, and recognized for significant research contributions.

  I am most skilled in: <mark>PHP</mark> and <mark>Laravel</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Peer-Interaction Programming Learning System
        link: new.pipls.net
      - layout: top-middle
        title: Cùng Học
        link: cunghoc.net
      - layout: top-middle
        title: Hung Vuong University Virtual Tour
        link: 360.hvu.edu.vn/V1/
      - layout: top-middle
        title: Hung Vuong University LMS
        link: elearning.hvu.edu.vn/
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # description: | # this will include new lines to allow paragraphs
        #   I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: International School, Vietnam National University
        link: is.vnu.edu.vn
        # link_text: boringcompany.com
        sub_title: Lecturer
        caption: April 2024 - Present
      - layout: left
        title: Hung Vuong University
        link: hvu.edu.vn
        # link_text: boringcompany.com
        sub_title: Lecturer, Head of Software Engineering Department
        caption: June 2021 - April 2024
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Dong Hwa University
        caption: 2014 - 2020
        sub_title: PhD in Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: left
        title: Hanoi University of Science and Technology
        caption: 2010 - 2012
        sub_title: Master in Computer Science
      - layout: left
        title: Hung Vuong University
        caption: 2006 - 2010
        sub_title: Bachelor in Computer Science

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Learning Technologies and Software Engineering, some of my other interests and hobbies are:
      - Spending time with my family
      - Exploring new ideas
      - Watching movies
      # - Knitting
      # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      # Look at this cool image  
      # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
